### ISSUE TITLE
Unavailable Request type.

### ISSUE THREAD

**Issue by aongeek** [OfficeDev/MAPI-Inspector-for-Fiddler#12]
Hi, 
I am seeing lot of requests where MAPI inspector shows  'Unavailable Request type.'. 

Please see the attached screenshots:

![screenshot 2016-01-26 14 14 27](https://cloud.githubusercontent.com/assets/7460763/12578129/58694fba-c438-11e5-8d4a-94c9922f634c.png)
![screenshot 2016-01-26 14 13 54](https://cloud.githubusercontent.com/assets/7460763/12578130/586a6ff8-c438-11e5-8a29-47276d3ccdc2.png)
![screenshot 2016-01-26 14 12 37](https://cloud.githubusercontent.com/assets/7460763/12578131/591a0ba2-c438-11e5-8ad5-dbc9bd3d5384.png)
![screenshot 2016-01-26 14 12 14](https://cloud.githubusercontent.com/assets/7460763/12578132/59791142-c438-11e5-9574-6117c17899b9.png)
![screenshot 2016-01-26 14 11 57](https://cloud.githubusercontent.com/assets/7460763/12578133/59bb9aa8-c438-11e5-9d28-314f6efcad90.png)

Steps to reproduce :
Using outlook, simply compose email with large inline text or attach a file and hit send. 

Environment: 
Windows 10 Pro.
Outlook (16.0.6326.1019) 32-bit. Office 365 Business. 
Fiddler 4.6.2.0.

Thanks.

**Comment by tarunchopra** [comment]
Hello aongeek - Can you please share your trace with me ?

**Comment by wazhar** [comment]
Hi Tarun,

Please find link below, 2 sessions exported in Fiddler's Session Archive format. 
https://www.dropbox.com/s/my0iwfpcoii8uav/trace.saz?dl=0

I observed this issue mostly in case of nspi requests. Please let me know if you need more data.

Thanks.

**Comment by tarunchopra** [comment]
Thanks,.

**Comment by tarunchopra** [comment]
Thanks.

**Comment by tarunchopra** [comment]
Hello Wazhar : 

We have updated MAPIFiddlerInspector.dll and MAPI.js at this location ( https://github.com/OfficeDev/MAPI-Inspector-for-Fiddler) which will resolve your issue. Please try these out and share your inputs.

Thanks.

**Comment by aongeek** [comment]
Hi, 
NSPI requests are being decoded now. However I have seen several IndexOutOfRangeExceptions. Seems like Decompression function is failing. I have seen such issues before ( with emsmdb requests) but could not conclusively determine where was the issue.  

Please see trace and screenshot below.
https://www.dropbox.com/s/thxhsux7ksnet7b/session_2916.saz?dl=0
https://www.dropbox.com/s/tqkdncfezh7uh6p/Screenshot%202016-01-29%2022.17.18.png?dl=0

Thanks.

**Comment by tarunchopra** [comment]
Glad that worked out. One small request ; shall we close this issue and open a new one for 'IndexOutOfRangeExceptions' so that it's easily discoverable looking at the subject line ?

**Comment by aongeek** [comment]
I agree. Please go ahead.

**Comment by tarunchopra** [comment]
Opened a new issue to track - IndexOutOfRangeExceptions exception. (https://github.com/OfficeDev/MAPI-Inspector-for-Fiddler/issues/15 )

**Comment by tarunchopra** [comment]
Wazhar : Would request you to close this issue.

**Comment by aongeek** [comment]
Resolved and verified.

**Comment by tarunchopra** [comment]
Wazhar : This issue (https://github.com/OfficeDev/MAPI-Inspector-for-Fiddler/issues/15 ) is resolved now. Please get the latest binary set and give it a shot.
